### ISSUE TITLE
Default placeholder (*format) not up to date with Python 3's sqlite module

### ISSUE THREAD

**Issue by dinosawrusrex** [hashedin/jinjasql#21]
Just wondering if this is a necessary fix just pertaining to using Jinjasql with sqlite3?

According to [Python 3's Sqlite3 documentation](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.execute), sqlite3 only accepts two kinds of placeholders when parameterising queries: question mark and named style. Would it be necessary to set the default `param_style` to be `qmark`?

**Comment by sripathikrishnan** [comment]
Yes, for sqlite, you should set the param_style to `qmark`. Closing this issue as there isn't a defect or feature. Thanks!
