### ISSUE TITLE
Support rendering named arguments with %(name)s placeholders

### ISSUE THREAD

**Issue by jfkw** [hashedin/jinjasql#5]
It would be nice to have a mode for rendering SQL arguments with %(name)s placeholders, with the names coming from the template and the bind parameters return value as dictionary instead of list.

http://initd.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

```
select username, sum(spend)
from transactions
where start_date > {{request.start_date}}
and end_date < {{request.end_date}}
{% if request.organization %}
and organization = {{request.organization}}
{% endif %}
```
```
select username, sum(spend)
from transaction
where start_date > %(start_date)s
and end_date < %(end_date)s
and organization = %(organization)s
```
It may be that only some database drivers can use named placeholders. It should be possible to configure this mode as default when instantiating JinjaSQL so templates and subsequent API calls don't need to pass that detail around:

`JinjaSql(named_placeholders=True)`

**Comment by sripathikrishnan** [comment]
I like the idea, and will get this issue fixed. Thanks for the suggestion!

**Comment by sripathikrishnan** [comment]
@jfkw I went a step further and supported multiple types of place holders. See the release notes over here - https://github.com/hashedin/jinjasql/releases/tag/v0.1.5, or [this section in the readme](https://github.com/hashedin/jinjasql#multiple-param-styles)
