### ISSUE TITLE
Write tests for param_style = named and pyformat

### ISSUE THREAD

**Issue by sripathikrishnan** [hashedin/jinjasql#7]
named and pyformat create random variable names to avoid conflicts. As a result, navie test cases will fail. Need to mock Random() object or seed it so that tests are deterministic.

**Comment by dckc** [comment]
why use random variable names at all? why not just use a counter?

**Comment by sripathikrishnan** [comment]
With https://github.com/hashedin/jinjasql/commit/c81795b9280f3815f08b3b19df61868c6265bf1b, this is no longer needed. Variable names use 128 bit random, and we are unlikely to get a conflict from that.
