### ISSUE TITLE
use jinjasql without django?

### ISSUE THREAD

**Issue by dckc** [hashedin/jinjasql#8]
I was a little surprised to find `django` in `requirements.txt`. So I looked at how it was used. As far as I can tell, it's used only in tests.

I'd like to be able to use this package without pulling in all of django.

**Comment by dckc** [comment]
never mind... now I remember `install_requires` from `setup.py` is where I should have looked; `requirements.txt` isn't as relevant to my use case.

**Comment by sripathikrishnan** [comment]
@dckc Hey, no worries :) 

For posterity - Django isn't necessary at all. But we want to be sure that jinjasql plays well with django - so we have a unit test for it. And that's why you'll find django in requirements.txt.
